# -*- coding: utf-8 -*-
"""
Created on Fri Dec 24 01:44:23 2021

@author: 邵键帆
"""



"""
This program is aimed at face detection
"""

#import the relevant package
import numpy as np
from convolution import show_with_matplotlib,show_with_matplotlib_array,bgr_imread,image_merge
from color_trans import bgr2hsv,image_range_capture



################################################## skin color face detection #####################################################

#define a class to execute the bgr skin color detection
class bgr_skin_color_detection():
    
    #initialize the relevant parameters for the bgr_skin_color_detection
    def __init__(self,image):
        #image: the bgr-form image
        self.image=image
    
    
    

    #return a skin capture colorful image generated by bgr image based on the 'RGB-H-CbCr Skin Color Model For Human Face detection'
    def bgr_skin_color_detection_color(self):
        capture_image=np.ones(self.image.shape,dtype="uint8")*255
        one_channel=self.image[:,:,0]
        for i in range(one_channel.shape[0]):
            for j in range(one_channel.shape[1]):
                b,g,r=self.image[i,j,0],self.image[i,j,1],self.image[i,j,2]
                e1=bool((r > 95) and (g > 40) and (b > 20) and ((max(r, max(g, b)) - min(r, min(g, b))) > 15) and (
                abs(int(r) - int(g)) > 15) and (r > g) and (r > b))
                e2 = bool((r > 220) and (g > 210) and (b > 170) and (abs(int(r) - int(g)) <= 15) and (r > b) and (g > b))
                if e1 or e2:
                    capture_image[i,j,:]=self.image[i,j,:]
        return capture_image
    
    
    #return a skin caputre colorful image generated hsv turned from bgr.
    def bgr_to_hsv_skin_color_detection_color(self):
        hsv_image=bgr2hsv(self.image)
        lower_array=np.array([0,48,80])
        upper_array=np.array([20,255,255])
        hsv_skin_color_detection_class=image_range_capture(lower_array,upper_array,hsv_image)
        hsv_skin_color_detection_color=hsv_skin_color_detection_class.image_range_color()
        return hsv_skin_color_detection_color
    
    #return a skin capture black image generated by bgr image, also based on aforementioned model 
    def bgr_skin_color_detection_black(self):
        capture_image=np.ones(self.image.shape,dtype="uint8")*0
        one_channel=self.image[:,:,0]
        for i in range(one_channel.shape[0]):
            for j in range(one_channel.shape[1]):
                b,g,r=self.image[i,j,0],self.image[i,j,1],self.image[i,j,2]
                e1=bool((r > 95) and (g > 40) and (b > 20) and ((max(r, max(g, b)) - min(r, min(g, b))) > 15) and (
                abs(int(r) - int(g)) > 15) and (r > g) and (r > b))
                e2 = bool((r > 220) and (g > 210) and (b > 170) and (abs(int(r) - int(g)) <= 15) and (r > b) and (g > b))
                if e1 or e2:
                    capture_image[i,j,:]=np.array([255,255,255])
        return capture_image
    #return a skin capture black image generated by hsv turned from the bgr image
    def bgr_to_hsv_skin_color_detection_black(self):
        hsv_image=bgr2hsv(self.image)
        lower_array=np.array([0,48,80])
        upper_array=np.array([20,255,255])
        hsv_skin_color_detection_class=image_range_capture(lower_array,upper_array,hsv_image)
        hsv_skin_color_detection_black=hsv_skin_color_detection_class.image_range_black()
        return hsv_skin_color_detection_black






################################################## skin color face detection #####################################################



############################################################################################## TEST ##############################################################################


"""

kids_image=bgr_imread("pics/kids.png")
kids_image_skin_color_detection=bgr_skin_color_detection(kids_image)
show_with_matplotlib(kids_image_skin_color_detection.bgr_skin_color_detection_color(),"bgr_kids_skin_color_detection_color")
show_with_matplotlib(kids_image_skin_color_detection.bgr_to_hsv_skin_color_detection_color(),"bgr_to_hsv_kids_skin_color_detection_color")
show_with_matplotlib(kids_image_skin_color_detection.bgr_skin_color_detection_black(),"bgr_kids_skin_color_detection_black")
show_with_matplotlib(kids_image_skin_color_detection.bgr_to_hsv_skin_color_detection_black(),"bgr_to_hsv_kids_skin_color_detection")

"""




############################################################################################## TEST ##############################################################################

